"""empty message

Revision ID: a47b31fc8df4
Revises: 
Create Date: 2023-09-16 13:52:40.345217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47b31fc8df4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('came_from', sa.Enum('web_search', 'social_networks', 'street_ads', name='camefromenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('auth',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('site', 'CRM', 'tgAdmin', name='authtypeenum'), nullable=False),
    sa.Column('refresh', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject')
    )
    op.create_index(op.f('ix_auth_subject'), 'auth', ['subject'], unique=False)
    op.create_table('employers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'seller', name='employeeroleenum'), nullable=False),
    sa.Column('telegram_chat_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    op.drop_index(op.f('ix_auth_subject'), table_name='auth')
    op.drop_table('auth')
    op.drop_table('users')
    # ### end Alembic commands ###
